### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Timboman** [Al12rs/modorganizer-game_generic#4]
Would it be possible to make this plugin function while MO2 is in Portable mode?
As it stands it only seems to work when you create a local MO2 instance and if you attempt to change the pathing back to the root MO2 folder you launched it from it just stops launching entirely.

I love the idea of making MO2 work for other games besides the usual BGS affair, but I'd also like to potentially use this as a means of creating Wabbajack sharable MO2 setups for other games too, which requires that it function in a self contained portable instance of MO2.

**Comment by Al12rs** [comment]
Why wouldn't this work?

**Comment by Al12rs** [comment]
Plugin works fine on portable here. You obviously need to have a clean Mo2 installation with no other game being managed already, then select portable and choose Browse to select a random target directory.
Please reopen if you still have issues.
